apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: true
    path: dev
    repoURL: 'git@github.com:justindav1s/shop-app-argocd-dev.git'
    targetRevision: HEAD